CREATE TABLE Admin
(
  AdminId INT IDENTITY(1,1) NOT NULL,
  Username VARCHAR(255) Unique NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Email VARCHAR(255) Unique NOT NULL,
  Role VARCHAR(50) NOT NULL,
  PRIMARY KEY (AdminId),
  FOREIGN KEY (Role) References Role(RoleName) ON UPDATE NO ACTION
 );

 CREATE TABLE TourPackage
(
  PackageId INT IDENTITY(1,1) NOT NULL,
  Name VARCHAR(255) NOT NULL,
  Price FLOAT NOT NULL,
  Cost FLOAT NOT NULL,
  Dmin INT NOT NULL,
  Dmax INT NOT NULL,
  AdminId INT NOT NULL,
  PRIMARY KEY (PackageId),
  FOREIGN KEY (AdminId) REFERENCES Admin(AdminId) ON UPDATE CASCADE
);

CREATE TABLE Season
(
  SeasonId INT IDENTITY(1,1) NOT NULL,
  Name VARCHAR(255) NOT NULL,
  StartDate DATE NOT NULL,
  EndDate DATE NOT NULL,
  AdminId INT NOT NULL,
  PRIMARY KEY (SeasonId),
  FOREIGN KEY (AdminId) REFERENCES Admin(AdminId) ON UPDATE CASCADE
);

CREATE TABLE PackageSeason
(
  PackageSeasonId INT IDENTITY(1,1) NOT NULL,
  Demand INT NOT NULL,
  PackageId INT NOT NULL,
  SeasonId INT NOT NULL,
  PRIMARY KEY (PackageSeasonId),
  FOREIGN KEY (PackageId) REFERENCES TourPackage(PackageId) ON UPDATE NO ACTION,
  FOREIGN KEY (SeasonId) REFERENCES Season(SeasonId) ON UPDATE NO ACTION
);

CREATE TABLE Resource
(
  ResourceId INT IDENTITY(1,1) NOT NULL,
  Name VARCHAR(255) NOT NULL,
  Cost FLOAT NOT NULL,
  AvailableAmount INT NOT NULL,
  AdminId INT NOT NULL,
  PRIMARY KEY (ResourceId),
  FOREIGN KEY (AdminId) REFERENCES Admin(AdminId) ON UPDATE CASCADE
);

CREATE TABLE Budget
(
  BudgetId INT IDENTITY(1,1) NOT NULL,
  ResourceBudget FLOAT NOT NULL,
  ResourceId INT NOT NULL,
  SeasonId INT NOT NULL,
  AdminId INT NOT NULL,
  PRIMARY KEY (BudgetId),
  FOREIGN KEY (AdminId) REFERENCES Admin(AdminId) ON UPDATE CASCADE,
  FOREIGN KEY (SeasonId) REFERENCES Season(SeasonId) ON UPDATE NO ACTION,
  FOREIGN KEY (ResourceId) REFERENCES Resource(ResourceId) ON UPDATE NO ACTION
);

CREATE TABLE ResourceAllocation
(
  ResourceAllocationId INT IDENTITY(1,1) NOT NULL,
  AllocationAmount INT NOT NULL,
  PackageSeasonId INT NOT NULL,
  ResourceId INT NOT NULL,
  PRIMARY KEY (ResourceAllocationId),
  FOREIGN KEY (PackageSeasonId) REFERENCES PackageSeason(PackageSeasonId) ON UPDATE NO ACTION,
  FOREIGN KEY (ResourceId) REFERENCES Resource(ResourceId) ON UPDATE NO ACTION
);

CREATE TABLE Role
(
RoleId INT IDENTITY (1,1) NOT NULL,
RoleName VARCHAR(255) NOT NULL,
Primary Key(RoleId)
);




